# Generated by Django 6.0.6 on 2026-07-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
