# Generated by Django 6.0.6 on 2026-07-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
