# Generated by Django 6.0.6 on 2026-07-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('mobile', 'Mobile Money'), ('credit', 'Credit Card'), ('savings', 'Savings')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('CAD', 'Canada Dollars'), ('USD', 'US Dollars'), ('EUR', 'Euro'), ('XAF', 'Center Africa')], default='CAD', max_length=10),
        ),
    ]
