# Generated by Django 6.0.6 on 2026-07-11 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='folder', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name')},
        ),
    ]
